### ISSUE TITLE
`getreginfo()` raises session error in Vim

### ISSUE THREAD

**Issue by Milly** [vim-denops/deno-denops-std#155]
Session error is occurred when `getreginfo()` called in Vim.

test plugin.
```typescript
// runtimepath/denops/foo/main.ts
import {
  getreg,
  getreginfo,
  getregtype,
  setreg,
} from "https://deno.land/x/denops_std@v3.9.1/function/mod.ts";
import type { Denops } from "https://deno.land/x/denops_std@v3.9.1/mod.ts";

export async function main(denops: Denops) {
  await setreg(denops, "a", "foo"); // works
  const reg = await getreg(denops, "a"); // works
  console.log({ reg });
  const regtype = await getregtype(denops, "a"); // works
  console.log({ regtype });
  const reginfo = await getreginfo(denops, "a"); // error in Vim, works in NeoVim
  console.log({ reginfo });
}
```

Denops server outputs in Vim:
```
{ reg: [ "foo" ] }
{ regtype: "v" }
Unexpected error occured in session: Error: Unexpected COMMA (",") in state VALUE
```

Denops server outputs in NeoVim:
```
{ reg: [ "foo" ] }
{ regtype: "v" }
{ reginfo: { regcontents: [ "foo" ], isunnamed: false, regtype: "v" } }
```

**Comment by lambdalisue** [comment]
Could you tell me the version of Vim and Neovim you've tested?

**Comment by Milly** [comment]
Issue occurred versions:
- gVim.exe 9.0.883 (Windows, installed with chocolatey)
- VIM 9.0.885 (Linux, installed with brew)

No issue occurred versions:
- nvim.exe v0.8.0-1210-gd367ed9b2 (Windows, installed with chocolatey)
- NVIM v0.8.1 (Linux, installed with brew)

**Comment by Milly** [comment]
vim/vim#11598

**Comment by Milly** [comment]
This issue fixed at Vim v9.0.0936 vim/vim@82946e143.

**Comment by lambdalisue** [comment]
Do you think we can do something for this? Any workaround for old Vim?

**Comment by Milly** [comment]
We already have [Workaround function for Vim RPC call](https://github.com/vim-denops/denops.vim/blob/v3.2.0/autoload/denops/api/vim.vim#L5) in denops.vim.
So it would be possible to insert behavior there.
I think it can not be implemented in deno-denops-std side.

**Comment by lambdalisue** [comment]
It seems re-defining `isunnamed` fix the issue on old Vim as well so I've added a workaround on #158.
