### ISSUE TITLE
[cursor] possible zero-based column behavior in cursor

### ISSUE THREAD

**Issue by dmfay** [vim-denops/deno-denops-std#185]
hello! I noticed [ddu-source-rg](https://github.com/shun/ddu-source-rg) started placing the cursor one column too early. For example when searching for the word `filter` and selecting this matching line from the ddu-source-rg docs:

```
    " "ddu-filter-converter_display_word".
```

the cursor should be on the `f` in `filter` (column 12) but instead it is on the dash in column 11. I have checked ddu-source-rg and ddu-kind-file and see the expected column 12 value in both those places, when [defining](https://github.com/shun/ddu-source-rg/blob/main/denops/%40ddu-sources/rg.ts#L122) and [executing](https://github.com/Shougo/ddu-kind-file/blob/main/denops/%40ddu-kinds/file.ts#L348) an action respectively. It seems to be passing 12 to denops' `cursor` but the final column is 11.

denops.vim commit: 8f3899de
ddu.vim commit: 974a1b41
ddu-kind-file commit: ca1788c4
ddu-source-rg commit: 3eff290c

<details><summary>Here's a sample (n)vimrc which reproduces the issue.</summary>

```
if has('vim_starting')
  let s:config_path = stdpath('cache')
  for s:repo in [
    \ 'vim-denops/denops.vim',
    \ 'Shougo/ddu.vim',
    \ 'Shougo/ddu-ui-ff',
    \ 'Shougo/ddu-kind-file',
    \ 'shun/ddu-source-rg',
    \ 'Shougo/ddu-filter-matcher_substring',
  \ ]
    let s:path = s:config_path . '/../dein/repos/github.com/' . s:repo
    let &g:rtp .= ',' . s:path
  endfor
endif

call ddu#custom#patch_global(#{
  \   ui: 'ff',
  \   uiParams: #{
  \     ff: #{
  \       startFilter: v:true,
  \       ignoreEmpty: v:false,
  \       autoResize: v:false,
  \     }
  \   },
  \   kindOptions: #{
  \     file: #{
  \       defaultAction: 'open',
  \     },
  \   },
  \   sources: [
  \     #{ name: 'rg', },
  \   ],
  \   sourceParams: #{
  \     rg: #{
  \       args: ['--column', '--no-heading', '--smart-case', '--color', 'never'],
  \       highlights: #{path: 'Url'},
  \     },
  \   },
  \ })

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer> <CR>
    \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  inoremap <buffer> <Esc>
    \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  inoremap <buffer> <C-j>
    \ <Cmd>call ddu#ui#ff#execute(
    \ "call cursor(line('.')+1,0)<Bar>redraw")<CR>
  inoremap <buffer> <C-k>
    \ <Cmd>call ddu#ui#ff#execute(
    \ "call cursor(line('.')-1,0)<Bar>redraw")<CR>
endfunction

nnoremap <space>/
  \ :call ddu#start(#{
  \   sources: [#{name: 'rg',}],
  \   sourceParams: #{rg: #{input: input('Pattern: ')}}
  \ })<CR>
```
</details>

\<space\>-/ and supply a search string, then press enter to choose the first result.

**Comment by lambdalisue** [comment]
I'm not sure what is the issue here but the column in the `cursor` starts from 1 as the documentation mentioned. This is Vim's design and denops does not touch that.

https://github.com/vim-denops/deno-denops-std/blob/cf25ec010f2b8abf93ba5c278898f27432b32f3e/denops_std/function/cursor.ts#L168-L169

**Comment by Shougo** [comment]
OK.   Reproduced.  It is not the problem of `denops.vim`.
It is the problem of `ddu-kind-file`.

**Comment by Shougo** [comment]
@dmfay Please update `ddu-kind-file`.
